#
# GEANT4 simulation of the Apollon 2022 experiment.
# Geometry has been derived from the FLUKA simulation of the same experiment.
# 
# Macro file for the Apollon simulation
# Last edited: 13/02/2022
#

# Set verbosity level
/control/verbose 1
/run/verbose 1

# Initialise run manager
/run/initialize

# Activate visualisation for tracks/hits
#/control/execute vis.mac

# Activate beam
/run/printProgress 1000
/run/beamOn 1000
