#
# GEANT4 simulation of the Apollon 2022 experiment.
# Geometry has been derived from the FLUKA simulation of the same experiment.
# 
# Macro file for the Apollon simulation
# Last edited: 13/02/2022
#

# Set verbosity level
/control/verbose 1
/run/verbose 1

# Initialise run manager
/run/initialize

# Visualisation commands
/vis/open OGLIX  600x600-0+0
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 90. 0.
/vis/scene/add/axes 0 0 0 1 cm
/vis/viewer/zoom 5.
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/add/hits
/vis/enable

# Activate beam
/run/printProgress 10
/run/beamOn 100
