# Visualisation commands
/vis/open OGL  600x600-0+0
/vis/drawVolume
/vis/viewer/panTo 0 0
/vis/viewer/set/viewpointThetaPhi 45. 30.
/vis/scene/add/axes 0 0 0 25 cm
/vis/viewer/zoom 4.
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/add/hits
/vis/enable