//
// GEANT4 simulation of the Apollon 2022 experiment.
// Geometry has been derived from the FLUKA simulation of the same experiment.
// 
// Macro file for processing tracks from Geant4 simulation.
// Last edited: 17/02/2022
//

#include <iostream>
#include <string>
#include <vector>
#include <stdexcept>
#include <algorithm>
#include <fstream>
#include <sstream>

#include "TTree.h"
#include "TChain.h"
#include "TFile.h"
#include "TH1.h"
#include "TH2.h"


int ProcessList(const std::string&, std::vector<std::string>&);

int apollon_tracks_process(std::string fnamelist) {
    // *
    // Open root file to write to
    //
    std::string suffix("_tracks");
    std::string foutname = fnamelist.substr(fnamelist.find_last_of("/")+1);
    foutname = foutname.substr(0, foutname.find_last_of("."));
    foutname += suffix + std::string(".root");

    TFile* fout = new TFile(foutname.c_str(), "RECREATE");
    // *
    // Defining histograms
    // *
    // Particle types
    int nbins = 50;
    TH1D* track_pdg = new TH1D("track_pdg", "", nbins, -25, 25); 

    // Creation processes
    nbins = 25;
    TH1D* track_procid = new TH1D("track_procid", "", nbins, 2000, 2025); 

    // Energy spectra
    nbins = 100;
    TH1D* track_vertex_kenergy = new TH1D("track_vertex_kenergy", "", nbins, 0., 1600.);
    TH1D* track_vertex_kenergy_electron = new TH1D("track_vertex_kenergy_electron", "", nbins, 0., 1600.);
    TH1D* track_vertex_kenergy_positron = new TH1D("track_vertex_kenergy_positron", "", nbins, 0., 1600.);

    // Creation vertices
    nbins = 200;
    const double VTXXMIN = -10.; // mm
    const double VTXXMAX = 10.;  // mm
    const double VTXYMIN = -10.; // mm
    const double VTXYMAX = 10.;  // mm
    const double VTXZMIN = -985.225; // mm
    const double VTXZMAX = -984.975; // mm

    TH2D* track_vtxx_vtxz = new TH2D("track_vtxx_vtxz", "", nbins, VTXXMIN, VTXXMAX, nbins, VTXZMIN, VTXZMAX);
    TH2D* track_vtxy_vtxz = new TH2D("track_vtxy_vtxz", "", nbins, VTXYMIN, VTXYMAX, nbins, VTXZMIN, VTXZMAX);
    TH1D* track_vtxz = new TH1D("track_vtxz", "", nbins, VTXZMIN, VTXZMAX);
    TH2D* track_vtxx_vtxz_electron = new TH2D("track_vtxx_vtxz_electron", "", nbins, VTXXMIN, VTXXMAX, nbins, VTXZMIN, VTXZMAX);
    TH2D* track_vtxy_vtxz_electron = new TH2D("track_vtxy_vtxz_electron", "", nbins, VTXYMIN, VTXYMAX, nbins, VTXZMIN, VTXZMAX);
    TH1D* track_vtxz_electron = new TH1D("track_vtxz_electron", "", nbins, VTXZMIN, VTXZMAX);
    TH2D* track_vtxx_vtxz_positron = new TH2D("track_vtxx_vtxz_positron", "", nbins, VTXXMIN, VTXXMAX, nbins, VTXZMIN, VTXZMAX);
    TH2D* track_vtxy_vtxz_positron = new TH2D("track_vtxy_vtxz_positron", "", nbins, VTXYMIN, VTXYMAX, nbins, VTXZMIN, VTXZMAX);
    TH1D* track_vtxz_positron = new TH1D("track_vtxz_positron", "", nbins, VTXZMIN, VTXZMAX);

    // End vertices
    nbins = 200;
    const double ENDXMIN = -10.; // mm
    const double ENDXMAX = 10.;  // mm
    const double ENDYMIN = -10.; // mm
    const double ENDYMAX = 10.;  // mm
    const double ENDZMIN = -985.225; // mm
    const double ENDZMAX = -984.975; // mm

    TH2D* track_endx_endz = new TH2D("track_endx_endz", "", nbins, ENDXMIN, ENDXMAX, nbins, ENDZMIN, ENDZMAX);
    TH2D* track_endy_endz = new TH2D("track_endy_endz", "", nbins, ENDYMIN, ENDYMAX, nbins, ENDZMIN, ENDZMAX);
    TH1D* track_endz = new TH1D("track_endz", "", nbins, ENDZMIN, ENDZMAX);
    TH2D* track_endx_endz_electron = new TH2D("track_endx_endz_electron", "", nbins, ENDXMIN, ENDXMAX, nbins, ENDZMIN, ENDZMAX);
    TH2D* track_endy_endz_electron = new TH2D("track_endy_endz_electron", "", nbins, ENDYMIN, ENDYMAX, nbins, ENDZMIN, ENDZMAX);
    TH1D* track_endz_electron = new TH1D("track_endz_electron", "", nbins, ENDZMIN, ENDZMAX);
    TH2D* track_endx_endz_positron = new TH2D("track_endx_endz_positron", "", nbins, ENDXMIN, ENDXMAX, nbins, ENDZMIN, ENDZMAX);
    TH2D* track_endy_endz_positron = new TH2D("track_endy_endz_positron", "", nbins, ENDYMIN, ENDYMAX, nbins, ENDZMIN, ENDZMAX);
    TH1D* track_endz_positron = new TH1D("track_endz_positron", "", nbins, ENDZMIN, ENDZMAX);

    // e+e- pairs generated by pair production
    nbins = 100;
    TH1D* track_vertex_kenergy_pairprod_electron = new TH1D("track_vertex_kenergy_pairprod_electron", "", nbins, 0., 1600.);
    TH1D* track_vertex_kenergy_pairprod_positron = new TH1D("track_vertex_kenergy_pairprod_positron", "", nbins, 0., 1600.);

    // *
    // Processing TChain
    // *
    std::vector<std::string> flist;
    ProcessList(fnamelist, flist);

    TChain* trackstree = new TChain("Tracks");
    std::for_each(flist.begin(), flist.end(), [trackstree](const std::string ss) { trackstree->Add(ss.c_str(), -1); });

    int evid, trackid, pdg, procid;
    double vtxx, vtxy, vtxz;
    double endx, endy, endz;
    double ekin;

    trackstree->SetBranchAddress("evid", &evid);
    trackstree->SetBranchAddress("trackid", &trackid);
    trackstree->SetBranchAddress("pdg", &pdg);
    trackstree->SetBranchAddress("procid", &procid);
    trackstree->SetBranchAddress("vtxx", &vtxx);
    trackstree->SetBranchAddress("vtxy", &vtxy);
    trackstree->SetBranchAddress("vtxz", &vtxz);
    trackstree->SetBranchAddress("endx", &endx);
    trackstree->SetBranchAddress("endy", &endy);
    trackstree->SetBranchAddress("endz", &endz);
    trackstree->SetBranchAddress("kEnergy", &ekin);

    Long64_t nevproc = trackstree->GetEntries();
    std::cout << "Events: " << nevproc << std::endl;

    for (Long64_t ii = 0; ii < nevproc; ++ii) {

        trackstree->GetEntry(ii);
        if (!(ii%1000000)) std::cout << ii << " entries processed" << std::endl;

        track_pdg->Fill(pdg);
        track_procid->Fill(procid);
        track_vtxz->Fill(vtxz);
        track_vtxx_vtxz->Fill(vtxz, vtxx);
        track_vtxy_vtxz->Fill(vtxz, vtxy);
        track_endx_endz->Fill(endx, endz);
        track_vertex_kenergy->Fill(ekin);

        if (pdg == 11) { // electrons
            track_vtxx_vtxz_electron->Fill(vtxz, vtxx);
            track_vtxy_vtxz_electron->Fill(vtxz, vtxy);
            track_vtxz_electron->Fill(vtxz);
            track_endx_endz_electron->Fill(endz, endx);
            track_endy_endz_electron->Fill(endz, endy);
            track_endz_electron->Fill(endz);
            track_vertex_kenergy_electron->Fill(ekin);
            if (procid==2014) track_vertex_kenergy_pairprod_electron->Fill(ekin);
        }
        else if (pdg == -11) { // positrons
            track_vtxx_vtxz_positron->Fill(vtxz, vtxx);
            track_vtxy_vtxz_positron->Fill(vtxz, vtxy);
            track_vtxz_positron->Fill(vtxz);
            track_endx_endz_positron->Fill(endz, endx);
            track_endy_endz_positron->Fill(endz, endy);
            track_endz_positron->Fill(endz);
            track_vertex_kenergy_positron->Fill(ekin);
            if (procid==2014) track_vertex_kenergy_pairprod_positron->Fill(ekin);
        }
    }

    fout->Write();
    fout->Close();

    return 0;
}

int ProcessList(const std::string& fnamelist, std::vector<std::string>& flist) {

    std::fstream fdata;
    fdata.open(fnamelist, std::ios::in);
    if(!fdata.is_open()) {
        throw std::runtime_error(std::string("Error opening file ") + fnamelist);
        return -1;
    }

    unsigned long lid = 0;
    while(!fdata.eof()) {
        std::string fname;
        fdata >> fname;
        if(!fdata.fail()) {
            flist.push_back(fname);
        }
        else if (fdata.eof()) {
            break;
        }
        else {
            std::cout << "ProcessList(..)  :  Error reading data from the file " << fnamelist 
                << ",  line: " << lid << ". Exit." << std::endl;
            fdata.close();
            return -2;
        }
        ++lid;
    }

    fdata.close();
    return 0;
}
